import {createRouter,createWebHistory,type RouteRecordRaw} from 'vue-router'
import {getToken} from '@/utils/auth'
import AdminLayout from '@/layouts/AdminLayout.vue'
const contentModules=[['patterns','纹样素材','pattern'],['documents','文献资料','document'],['creations','共创作品','creation'],['inheritors','传承人介绍','inheritor'],['application-cases','应用案例','application_case']] as const
const catalogModules=[['banners','Banner 管理','banners'],['categories','分类管理','categories'],['tags','标签管理','tags'],['pages','页面内容','pages']] as const
const children:RouteRecordRaw[]=[{path:'',redirect:'/dashboard'},{path:'dashboard',name:'dashboard',component:()=>import('@/views/DashboardView.vue'),meta:{title:'首页概览'}},...contentModules.map(([path,title,resourceType])=>({path,name:path,component:()=>import('@/views/ContentManagerView.vue'),meta:{title,resourceType}})),...catalogModules.map(([path,title,catalogKind])=>({path,name:path,component:()=>import('@/views/CatalogManagerView.vue'),meta:{title,catalogKind}})),{path:'featured',name:'featured',component:()=>import('@/views/FeaturedView.vue'),meta:{title:'首页推荐'}},{path:'media-files',name:'media-files',component:()=>import('@/views/MediaFilesView.vue'),meta:{title:'文件管理'}},{path:'settings',name:'settings',component:()=>import('@/views/SettingsView.vue'),meta:{title:'网站设置'}},{path:'admin-users',name:'admin-users',component:()=>import('@/views/AdminUsersView.vue'),meta:{title:'管理员管理'}}]
const router=createRouter({history:createWebHistory(import.meta.env.BASE_URL),routes:[{path:'/login',name:'login',component:()=>import('@/views/LoginView.vue'),meta:{public:true,title:'管理员登录'}},{path:'/',component:AdminLayout,children},{path:'/:pathMatch(.*)*',redirect:'/dashboard'}]})
router.beforeEach(to=>{document.title=`${String(to.meta.title||'管理后台')} · 土族盘绣素材库`;const token=getToken();if(!to.meta.public&&!token)return{name:'login',query:{redirect:to.fullPath}};if(to.name==='login'&&token)return{name:'dashboard'};return true})
export default router
