<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage} from 'element-plus'
import {changePassword,createAdmin,listAdmins,updateAdmin,type AdminUserRecord} from '@/api/auth'
const loading=ref(false),dialog=ref(false),passwordDialog=ref(false),items=ref<AdminUserRecord[]>([])
const form=reactive({id:'',username:'',password:'',displayName:'',email:'',status:'active' as 'active'|'disabled'})
const passwordForm=reactive({currentPassword:'',newPassword:'',confirmPassword:''})
async function load(){loading.value=true;try{items.value=await listAdmins()}finally{loading.value=false}}
function add(){Object.assign(form,{id:'',username:'',password:'',displayName:'',email:'',status:'active'});dialog.value=true}
function edit(row:AdminUserRecord){Object.assign(form,{id:row.id,username:row.username,password:'',displayName:row.displayName,email:row.email||'',status:row.status});dialog.value=true}
async function save(){if(!form.username.trim()||!form.displayName.trim())return ElMessage.warning('请填写账号和显示名称');if(!form.id&&form.password.length<10)return ElMessage.warning('初始密码至少 10 位');if(form.id)await updateAdmin(form.id,{displayName:form.displayName,email:form.email||null,status:form.status});else await createAdmin({username:form.username,password:form.password,displayName:form.displayName,email:form.email||null});ElMessage.success('管理员已保存');dialog.value=false;await load()}
function openPassword(){Object.assign(passwordForm,{currentPassword:'',newPassword:'',confirmPassword:''});passwordDialog.value=true}
async function savePassword(){if(passwordForm.newPassword.length<10)return ElMessage.warning('新密码至少 10 位');if(passwordForm.newPassword!==passwordForm.confirmPassword)return ElMessage.warning('两次输入的新密码不一致');await changePassword({currentPassword:passwordForm.currentPassword,newPassword:passwordForm.newPassword});ElMessage.success('密码已修改');passwordDialog.value=false}
onMounted(load)
</script>
<template><section><div class="manager-head"><div><span class="eyebrow">ACCESS CONTROL</span><h1>管理员管理</h1><p>这里只维护 CMS 管理员，不创建普通用户。</p></div><div><el-button @click="openPassword">修改我的密码</el-button><el-button type="primary" @click="add">新增管理员</el-button></div></div><el-card><el-table v-loading="loading" :data="items"><el-table-column prop="username" label="账号"/><el-table-column prop="displayName" label="显示名称"/><el-table-column prop="email" label="邮箱"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='active'?'success':'info'">{{row.status==='active'?'启用':'禁用'}}</el-tag></template></el-table-column><el-table-column prop="lastLoginAt" label="最近登录"/><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button></template></el-table-column></el-table></el-card><el-dialog v-model="dialog" :title="form.id?'编辑管理员':'新增管理员'" width="520px"><el-form label-position="top"><el-form-item label="账号" required><el-input v-model="form.username" :disabled="Boolean(form.id)" maxlength="64"/></el-form-item><el-form-item v-if="!form.id" label="初始密码" required><el-input v-model="form.password" type="password" show-password/></el-form-item><el-form-item label="显示名称" required><el-input v-model="form.displayName"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item v-if="form.id" label="状态"><el-select v-model="form.status"><el-option label="启用" value="active"/><el-option label="禁用" value="disabled"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog><el-dialog v-model="passwordDialog" title="修改我的密码" width="480px"><el-form label-position="top"><el-form-item label="当前密码"><el-input v-model="passwordForm.currentPassword" type="password" show-password/></el-form-item><el-form-item label="新密码"><el-input v-model="passwordForm.newPassword" type="password" show-password/></el-form-item><el-form-item label="确认新密码"><el-input v-model="passwordForm.confirmPassword" type="password" show-password/></el-form-item></el-form><template #footer><el-button @click="passwordDialog=false">取消</el-button><el-button type="primary" @click="savePassword">确认修改</el-button></template></el-dialog></section></template>
