<script setup lang="ts">
import {computed,onMounted,reactive,ref,watch} from 'vue'
import {useRoute} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import ImageUploader from '@/components/ImageUploader.vue'
import MultiImageUploader from '@/components/MultiImageUploader.vue'
import FileUploader from '@/components/FileUploader.vue'
import RichTextEditor from '@/components/RichTextEditor.vue'
import type {UploadFileRecord} from '@/types/api'
import {addDownload,addPatternImage,deleteContent,deleteDownload,deletePatternImage,getContent,listContents,saveContent,setFeatured,setSort,setStatus,updatePatternImage,type ContentRecord,type ResourceType,type Status} from '@/api/content'
import {listCatalog,type CatalogRecord} from '@/api/catalog'
const route=useRoute(),type=computed(()=>route.meta.resourceType as ResourceType),title=computed(()=>String(route.meta.title)),loading=ref(false),saving=ref(false),items=ref<ContentRecord[]>([]),total=ref(0),drawer=ref(false),preview=ref(false),categories=ref<CatalogRecord[]>([]),tags=ref<CatalogRecord[]>([]),pendingFiles=ref<UploadFileRecord[]>([])
const q=reactive({page:1,pageSize:10,keyword:'',status:'',categoryId:undefined as number|undefined,sort:'default'})
const blank=()=>({id:undefined as number|undefined,title:'',coverImage:null as UploadFileRecord|null,categoryId:undefined as number|undefined,description:'',content:'',tags:[] as string[],status:'draft' as Status,sortOrder:0,isFeatured:false,sourceArea:'',applicationPart:'',craftType:'',mainColors:[] as string[],meaning:'',author:'',source:'',year:undefined as number|undefined,summary:'',creatorName:'',creationDate:'',level:'',region:'',birthYear:undefined as number|undefined,caseType:'',clientName:'',caseDate:'',images:[] as any[],downloadFiles:[] as any[]})
let form=reactive(blank())
const extras:Record<ResourceType,string[]>={pattern:['sourceArea','applicationPart','craftType','mainColors','meaning'],document:['author','source','year','summary'],creation:['creatorName','creationDate'],inheritor:['level','region','birthYear'],application_case:['caseType','clientName','caseDate']}
const labels:Record<string,string>={sourceArea:'来源地区',applicationPart:'应用部位',craftType:'工艺技法',mainColors:'主要色彩',meaning:'图案寓意',author:'作者',source:'来源',year:'年份',summary:'摘要',creatorName:'作者 / 创作者',creationDate:'创作日期',level:'级别',region:'地区',birthYear:'出生年份',caseType:'应用场景',clientName:'客户 / 单位',caseDate:'案例日期'}
const hasCategory=computed(()=>true)
const imageUrl=(url?:string)=>url?/^https?:/.test(url)?url:new URL(url,import.meta.env.VITE_API_BASE_URL.replace(/\/api\/?$/,'/')).toString():''
function normalizeArray(v:unknown){if(Array.isArray(v))return v as string[];try{return JSON.parse(String(v||'[]'))}catch{return []}}
async function load(){loading.value=true;try{const r=await listContents({...q,type:type.value,status:q.status||undefined});items.value=r.items;total.value=r.total}finally{loading.value=false}}
async function dictionaries(){const [c,t]=await Promise.all([listCatalog('categories',{page:1,pageSize:100,resourceType:type.value,status:'published'}),listCatalog('tags',{page:1,pageSize:100,status:'published'})]);categories.value=c.items;tags.value=t.items}
function create(){Object.assign(form,blank());pendingFiles.value=[];preview.value=false;drawer.value=true}
async function edit(row:ContentRecord,asPreview=false){const d=await getContent(type.value,row.id);Object.assign(form,blank(),d,{id:d.id,coverImage:d.cover_image?{id:'0',file_url:d.cover_image,file_name:'',file_size:0,file_type:'image'}:null,categoryId:d.category_id||undefined,sortOrder:d.sort_order||0,isFeatured:Boolean(d.is_featured),tags:normalizeArray(d.tags),mainColors:normalizeArray(d.main_colors),sourceArea:d.source_area||'',applicationPart:d.application_part||'',craftType:d.craft_type||'',creatorName:d.creator_name||'',creationDate:d.creation_date?.toString().slice(0,10)||'',birthYear:d.birth_year||undefined,caseType:d.case_type||'',clientName:d.client_name||'',caseDate:d.case_date?.toString().slice(0,10)||'',downloadFiles:d.downloadFiles||[]});pendingFiles.value=[];preview.value=asPreview;drawer.value=true}
function payload(status?:Status){const p:any={title:form.title,coverImage:form.coverImage?.file_url||null,description:form.description||null,content:form.content||null,tags:form.tags,status:status||form.status,sortOrder:form.sortOrder,isFeatured:form.isFeatured};if(hasCategory.value)p.categoryId=form.categoryId||null;for(const k of extras[type.value])p[k]=(form as any)[k]||(k==='mainColors'?[]:null);return p}
async function save(status?:Status){if(!form.title.trim())return ElMessage.warning('请输入标题');saving.value=true;try{const saved=await saveContent(type.value,form.id,payload(status));form.id=saved.id;for(const f of pendingFiles.value)await addDownload(type.value,saved.id,f);pendingFiles.value=[];ElMessage.success(status==='published'?'内容已上架':'保存成功');drawer.value=false;await load()}finally{saving.value=false}}
async function changeStatus(row:ContentRecord,status:Status){await setStatus(type.value,row.id,status);ElMessage.success(status==='published'?'已上架':'已下架');await load()}
async function remove(row:ContentRecord){await ElMessageBox.confirm(`确定删除“${row.title}”吗？删除后无法恢复。`,'删除确认',{type:'warning'});await deleteContent(type.value,row.id);ElMessage.success('删除成功');await load()}
async function sortChanged(row:ContentRecord){await setSort(type.value,row.id,Number(row.sort_order));ElMessage.success('排序已更新')}
async function featureChanged(row:ContentRecord){await setFeatured(type.value,row.id,Boolean(row.is_featured));ElMessage.success('推荐状态已更新')}
async function uploadedImages(files:UploadFileRecord[]){if(!form.id){ElMessage.warning('请先保存草稿，再绑定详情图片');return}for(const f of files){const img=await addPatternImage(form.id,{imageUrl:f.file_url,altText:form.title,sortOrder:form.images.length*10});form.images.push(img)}}
async function imageOrder(img:any){await updatePatternImage(img.id,{imageUrl:img.image_url,altText:img.alt_text,sortOrder:Number(img.sort_order)});ElMessage.success('图片顺序已更新')}
async function removeImage(img:any){await deletePatternImage(img.id);form.images=form.images.filter((x:any)=>x.id!==img.id)}
async function removeFile(file:any){await deleteDownload(file.id);form.downloadFiles=form.downloadFiles.filter((x:any)=>x.id!==file.id)}
watch(type,async()=>{q.page=1;await Promise.all([load(),dictionaries()])});onMounted(()=>Promise.all([load(),dictionaries()]))
</script>
<template><section><div class="manager-head"><div><span class="eyebrow">CONTENT CMS</span><h1>{{title}}</h1></div><el-button type="primary" @click="create">新增内容</el-button></div>
<el-card><el-form inline><el-form-item label="搜索"><el-input v-model="q.keyword" clearable placeholder="标题或简介" @keyup.enter="q.page=1;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="q.status" clearable style="width:130px"><el-option label="草稿" value="draft"/><el-option label="已上架" value="published"/><el-option label="已下架" value="offline"/></el-select></el-form-item><el-form-item v-if="hasCategory" label="分类"><el-select v-model="q.categoryId" clearable style="width:160px"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="排序"><el-select v-model="q.sort" style="width:130px"><el-option label="默认" value="default"/><el-option label="最新" value="latest"/><el-option label="热门" value="popular"/><el-option label="下载量" value="downloads"/></el-select></el-form-item><el-button type="primary" @click="q.page=1;load()">查询</el-button><el-button @click="Object.assign(q,{page:1,keyword:'',status:'',categoryId:undefined,sort:'default'});load()">重置</el-button></el-form>
<el-table v-loading="loading" :data="items"><el-table-column label="封面" width="78"><template #default="{row}"><el-image v-if="row.cover_image" :src="imageUrl(row.cover_image)" fit="cover" class="thumb"/></template></el-table-column><el-table-column prop="title" label="标题" min-width="180"/><el-table-column label="状态" width="92"><template #default="{row}"><el-tag :type="row.status==='published'?'success':row.status==='offline'?'info':'warning'">{{row.status==='published'?'已上架':row.status==='offline'?'已下架':'草稿'}}</el-tag></template></el-table-column><el-table-column label="排序" width="105"><template #default="{row}"><el-input-number v-model="row.sort_order" size="small" controls-position="right" @change="sortChanged(row)"/></template></el-table-column><el-table-column label="首页推荐" width="100"><template #default="{row}"><el-switch v-model="row.is_featured" :active-value="1" :inactive-value="0" @change="featureChanged(row)"/></template></el-table-column><el-table-column label="操作" width="270" fixed="right"><template #default="{row}"><el-button link @click="edit(row,true)">预览</el-button><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button v-if="row.status!=='published'" link type="success" @click="changeStatus(row,'published')">上架</el-button><el-button v-else link @click="changeStatus(row,'offline')">下架</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="q.page" v-model:page-size="q.pageSize" layout="total, sizes, prev, pager, next" :total="total" @change="load"/></el-card>
<el-drawer v-model="drawer" :title="preview?'内容预览':form.id?'编辑内容':'新增内容'" size="720px"><div v-if="preview" class="content-preview"><img v-if="form.coverImage" :src="imageUrl(form.coverImage.file_url)"/><h1>{{form.title}}</h1><p>{{form.description}}</p><div v-html="form.content"/></div><el-form v-else label-position="top"><el-row :gutter="18"><el-col :span="16"><el-form-item label="标题" required><el-input v-model="form.title"/></el-form-item></el-col><el-col :span="8"><el-form-item label="排序"><el-input-number v-model="form.sortOrder"/></el-form-item></el-col></el-row><el-form-item label="封面图"><ImageUploader v-model="form.coverImage"/></el-form-item><el-row :gutter="18"><el-col v-if="hasCategory" :span="12"><el-form-item label="分类"><el-select v-model="form.categoryId" clearable><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="标签"><el-select v-model="form.tags" multiple allow-create filterable><el-option v-for="t in tags" :key="t.id" :label="t.name" :value="t.name"/></el-select></el-form-item></el-col></el-row><template v-for="key in extras[type]" :key="key"><el-form-item :label="labels[key]"><el-select v-if="key==='mainColors'" v-model="form.mainColors" multiple allow-create filterable placeholder="输入色值，如 #C62828"/><el-input-number v-else-if="['year','birthYear'].includes(key)" v-model="(form as any)[key]"/><el-date-picker v-else-if="['creationDate','caseDate'].includes(key)" v-model="(form as any)[key]" value-format="YYYY-MM-DD"/><el-input v-else v-model="(form as any)[key]" :type="['meaning','summary'].includes(key)?'textarea':'text'"/></el-form-item></template><el-form-item label="简介 / 说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="正文"><RichTextEditor v-model="form.content"/></el-form-item><template v-if="type==='pattern'"><el-divider>详情图片</el-divider><MultiImageUploader @uploaded="uploadedImages"/><div v-for="img in form.images" :key="img.id" class="asset-row"><el-image :src="imageUrl(img.image_url)" class="thumb"/><el-input-number v-model="img.sort_order" @change="imageOrder(img)"/><el-button type="danger" link @click="removeImage(img)">删除</el-button></div></template><el-divider>下载附件</el-divider><FileUploader @update:model-value="v=>{if(v)pendingFiles.push(v)}"/><div v-for="f in form.downloadFiles" :key="f.id" class="asset-row"><a :href="imageUrl(f.file_url)" target="_blank">{{f.file_name}}</a><el-button type="danger" link @click="removeFile(f)">删除</el-button></div><el-form-item label="首页推荐"><el-switch v-model="form.isFeatured"/></el-form-item></el-form><template v-if="!preview" #footer><el-button @click="drawer=false">取消</el-button><el-button :loading="saving" @click="save('draft')">保存草稿</el-button><el-button type="primary" :loading="saving" @click="save('published')">保存并上架</el-button></template></el-drawer></section></template>
